ERROR    asyncio:base_events.py:1805 Exception in callback SyncBase._sync.<locals>.<lambda>(<Task finishe...been closed')>) at /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_sync_base.py:111
handle: <Handle SyncBase._sync.<locals>.<lambda>(<Task finishe...been closed')>) at /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_sync_base.py:111>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 111, in <lambda>
    task.add_done_callback(lambda _: g_self.switch())
                                     ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_browser_context.py", line 187, in <lambda>
    lambda params: self._on_request_finished(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_browser_context.py", line 592, in _on_request_finished
    page.emit(Page.Events.RequestFinished, request)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/base.py", line 208, in emit
    handled = self._call_handlers(event, args, kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/base.py", line 184, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/asyncio.py", line 53, in _emit_run
    self.emit("error", exc)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/base.py", line 211, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/base.py", line 169, in _emit_handle_potential_error
    raise error
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pyee/asyncio.py", line 51, in _emit_run
    coro: Any = f(*args, **kwargs)
                ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
           ^^^^^^^^
  File "/home/runner/work/playwright_tests_UI/playwright_tests_UI/conftest.py", line 66, in <lambda>
    "headers": request.response().headers,
               ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 342, in response
    return mapping.from_impl_nullable(self._sync(self._impl_obj.response()))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_network.py", line 190, in response
    return from_nullable_channel(await self._channel.send("response"))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 495, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed