{"name": "Применение невалидного промокода", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: : Tracing has been already started", "trace": "page = <Page url='about:blank'>, request = <SubRequest 'page_fixture' for <Function test_cart_aplying_a_invalid_promo_code[chromium]>>\n\n    @pytest.fixture(scope=\"function\")\n    def page_fixture(page, request):\n        page.set_viewport_size({\"width\": 1920, \"height\": 1080})\n    \n        # Начало записи трассировки\n        trace_path = os.path.join(os.getcwd(), f'traces/{request.node.name}.zip')\n>       page.context.tracing.start(screenshots=True, snapshots=True)\n\nconftest.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14769: in start\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_tracing.py:50: in start\n    trace_name = await self._connection.wrap_api_call(_inner_start, True)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001DF98756510>, cb = <function Tracing.start.<locals>._inner_start at 0x000001DF98DE9760>, is_internal = True\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n***REMOVED*** -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: : Tracing has been already started\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:514: Error"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1725376585586, "stop": 1725376585586, "uuid": "361dd9a3-c541-4e7c-b6b5-4cd4731c97d3", "historyId": "b9f176d0ec909dec7c9d55af21553544", "testCaseId": "962ca41b73ee01d956abfa54839a25a1", "fullName": "tests.test_cart#test_cart_aplying_a_invalid_promo_code", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cart"}, {"name": "host", "value": "garagenote-234"}, {"name": "thread", "value": "27968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cart"}]}