{"name": "Вернутся в корзину через нажатие на пространство вне окна", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: : Tracing has been already started", "trace": "page = <Page url='about:blank'>, request = <SubRequest 'page_fixture' for <Function test_back_to_cart_from_modal_2[chromium]>>\n\n    @pytest.fixture(scope=\"function\")\n    def page_fixture(page, request):\n        page.set_viewport_size({\"width\": 1920, \"height\": 1080})\n    \n        # Начало записи трассировки\n        trace_path = os.path.join(os.getcwd(), f'traces/{request.node.name}.zip')\n>       page.context.tracing.start(screenshots=True, snapshots=True)\n\nconftest.py:32: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:14769: in start\n    self._sync(\n.venv\\Lib\\site-packages\\playwright\\_impl\\_tracing.py:50: in start\n    trace_name = await self._connection.wrap_api_call(_inner_start, True)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <playwright._impl._connection.Connection object at 0x000001DF98756510>, cb = <function Tracing.start.<locals>._inner_start at 0x000001DF98AE1EE0>, is_internal = True\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.Error: : Tracing has been already started\n\n.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:514: Error"}, "parameters": [{"name": "browser_name", "value": "'chromium'"}], "start": 1725376588305, "stop": 1725376588305, "uuid": "a31f4862-0dcc-4246-809a-f9d0dae20ec3", "historyId": "c71985f56d3859bbc7827f11e5e37912", "testCaseId": "26d72290e3978a6223b4e2e0ebb7c021", "fullName": "tests.test_cart#test_back_to_cart_from_modal_2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cart"}, {"name": "host", "value": "garagenote-234"}, {"name": "thread", "value": "27968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cart"}]}